spring:
  application:
    name: likelion-spring

  datasource:
    url: jdbc:mysql://localhost:3306/testing1st
    username: root
    password: skatlsddong@02
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update